[build]
command = "pnpm install --no-frozen-lockfile && pnpm run build"
publish = ".next"

[build.environment]
NODE_ENV = "production"
NPM_FLAGS = "--no-frozen-lockfile"
node_version = "18"
NEXT_TELEMETRY_DISABLED = "1"
NEXT_SHARP_PATH = "/opt/buildhome/.npm-global/lib/node_modules/sharp"
NPM_CONFIG_PACKAGE_MANAGER = "pnpm"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
NEXT_TYPESCRIPT_COMPILE = "true"
NEXT_PUBLIC_BASE_PATH = ""

[[plugins]]
package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:;"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
