[build]
command = "npm install && npm run build"
publish = ".next"

[build.environment]
NODE_ENV = "production"
NPM_FLAGS = "--legacy-peer-deps"
node_version = "18"

[[plugins]]
package = "@netlify/plugin-nextjs"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
