[build]
command = "npm install --legacy-peer-deps && npm run build"
publish = ".next"

[build.environment]
NODE_ENV = "production"
NPM_FLAGS = "--legacy-peer-deps"
node_version = "18"
NEXT_TELEMETRY_DISABLED = "1"
NEXT_SHARP_PATH = "/opt/buildhome/.npm-global/lib/node_modules/sharp"
NPM_CONFIG_PACKAGE_MANAGER = "npm"

[[plugins]]
package = "@netlify/plugin-nextjs"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
