[build]
command = "pnpm install --no-frozen-lockfile && pnpm run build"
publish = ".next"

[build.environment]
NODE_ENV = "production"
NPM_FLAGS = "--no-frozen-lockfile"
node_version = "18"
NEXT_TELEMETRY_DISABLED = "1"
NEXT_SHARP_PATH = "/opt/buildhome/.npm-global/lib/node_modules/sharp"
NPM_CONFIG_PACKAGE_MANAGER = "pnpm"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
NEXT_TYPESCRIPT_COMPILE = "true"

[[plugins]]
package = "@netlify/plugin-nextjs"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
